#!/bin/bash

// TODO thats just a draft. It's not working yet! Please contact me, if you are interested in this script

// fetch learning rooms
wget https://www2.elearning.rwth-aachen.de/foyer/summary/default.aspx

// parse urls

// remove old urls from .gtk-bookmarks

// append to .gtk-bookmarks
davs://www2.elearning.rwth-aachen.de/ws10/10ws-09977/materials/documents L²P MMET Projekt
